/*(Copyright)

        Microsoft Copyright 2009, 2010, 2011, 2012, 2013
        Confidential Information

*/
/*(Auto)

    Automatically Generated by Part2Parser.pl

    Date: Jul 29, 2013
    Time: 10:39:59 AM

*/

#ifndef _BASETYPES_H
#define _BASETYPES_H

#include <stdint.h>

typedef uint8_t                  UINT8;
typedef uint8_t                  BYTE;
typedef int8_t                   INT8;
typedef uint16_t                 UINT16;
typedef int16_t                  INT16;
typedef uint32_t                 UINT32;
typedef int32_t                  INT32;
typedef uint64_t                 UINT64;
typedef int64_t                  INT64;
typedef int32_t					 DWORD;

typedef struct {
    UINT16        size;
    BYTE          buffer[1];
} TPM2B;

;
#endif
